# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainajTYQh.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class UiMainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(760, 790)
        MainWindow.setMinimumSize(QSize(760, 790))
        MainWindow.setBaseSize(QSize(760, 790))
        font = QFont()
        font.setFamily(u"Malgun Gothic")
        MainWindow.setFont(font)
        self.centralWidget = QWidget(MainWindow)
        self.centralWidget.setObjectName(u"centralWidget")
        self.grpSrc = QGroupBox(self.centralWidget)
        self.grpSrc.setObjectName(u"grpSrc")
        self.grpSrc.setGeometry(QRect(20, 20, 351, 211))
        self.leSrcHost = QLineEdit(self.grpSrc)
        self.leSrcHost.setObjectName(u"leSrcHost")
        self.leSrcHost.setGeometry(QRect(70, 60, 121, 20))
        self.lbSrcHost = QLabel(self.grpSrc)
        self.lbSrcHost.setObjectName(u"lbSrcHost")
        self.lbSrcHost.setGeometry(QRect(10, 60, 56, 20))
        self.lbSrcPort = QLabel(self.grpSrc)
        self.lbSrcPort.setObjectName(u"lbSrcPort")
        self.lbSrcPort.setGeometry(QRect(10, 90, 56, 20))
        self.leSrcPort = QLineEdit(self.grpSrc)
        self.leSrcPort.setObjectName(u"leSrcPort")
        self.leSrcPort.setGeometry(QRect(70, 90, 121, 20))
        self.lbSrcDB = QLabel(self.grpSrc)
        self.lbSrcDB.setObjectName(u"lbSrcDB")
        self.lbSrcDB.setGeometry(QRect(10, 120, 56, 20))
        self.leSrcDB = QLineEdit(self.grpSrc)
        self.leSrcDB.setObjectName(u"leSrcDB")
        self.leSrcDB.setGeometry(QRect(70, 120, 121, 20))
        self.lbSrcUser = QLabel(self.grpSrc)
        self.lbSrcUser.setObjectName(u"lbSrcUser")
        self.lbSrcUser.setGeometry(QRect(10, 150, 56, 20))
        self.leSrcUser = QLineEdit(self.grpSrc)
        self.leSrcUser.setObjectName(u"leSrcUser")
        self.leSrcUser.setGeometry(QRect(70, 150, 121, 20))
        self.lbSrcPasswd = QLabel(self.grpSrc)
        self.lbSrcPasswd.setObjectName(u"lbSrcPasswd")
        self.lbSrcPasswd.setGeometry(QRect(10, 180, 56, 20))
        self.leSrcPasswd = QLineEdit(self.grpSrc)
        self.leSrcPasswd.setObjectName(u"leSrcPasswd")
        self.leSrcPasswd.setGeometry(QRect(70, 180, 121, 20))
        self.lbSrcRdbms = QLabel(self.grpSrc)
        self.lbSrcRdbms.setObjectName(u"lbSrcRdbms")
        self.lbSrcRdbms.setGeometry(QRect(10, 30, 56, 20))
        self.cbSrcDbms = QComboBox(self.grpSrc)
        self.cbSrcDbms.addItem("")
        self.cbSrcDbms.setObjectName(u"cbSrcDbms")
        self.cbSrcDbms.setGeometry(QRect(70, 30, 121, 20))
        self.cbSrcDbms.setEditable(False)
        self.pbSrcTestConn = QPushButton(self.grpSrc)
        self.pbSrcTestConn.setObjectName(u"pbSrcTestConn")
        self.pbSrcTestConn.setGeometry(QRect(220, 30, 111, 23))
        self.pbSrcConn = QPushButton(self.grpSrc)
        self.pbSrcConn.setObjectName(u"pbSrcConn")
        self.pbSrcConn.setGeometry(QRect(220, 60, 111, 23))
        self.grpTgt = QGroupBox(self.centralWidget)
        self.grpTgt.setObjectName(u"grpTgt")
        self.grpTgt.setGeometry(QRect(380, 20, 361, 211))
        self.leTgtHost = QLineEdit(self.grpTgt)
        self.leTgtHost.setObjectName(u"leTgtHost")
        self.leTgtHost.setGeometry(QRect(70, 60, 121, 20))
        self.lbTgtHost = QLabel(self.grpTgt)
        self.lbTgtHost.setObjectName(u"lbTgtHost")
        self.lbTgtHost.setGeometry(QRect(10, 60, 56, 20))
        self.lbTgtPort = QLabel(self.grpTgt)
        self.lbTgtPort.setObjectName(u"lbTgtPort")
        self.lbTgtPort.setGeometry(QRect(10, 90, 56, 20))
        self.leTgtPort = QLineEdit(self.grpTgt)
        self.leTgtPort.setObjectName(u"leTgtPort")
        self.leTgtPort.setGeometry(QRect(70, 90, 121, 20))
        self.lbTgtDB = QLabel(self.grpTgt)
        self.lbTgtDB.setObjectName(u"lbTgtDB")
        self.lbTgtDB.setGeometry(QRect(10, 120, 56, 20))
        self.leTgtDB = QLineEdit(self.grpTgt)
        self.leTgtDB.setObjectName(u"leTgtDB")
        self.leTgtDB.setGeometry(QRect(70, 120, 121, 20))
        self.lbTgtUser = QLabel(self.grpTgt)
        self.lbTgtUser.setObjectName(u"lbTgtUser")
        self.lbTgtUser.setGeometry(QRect(10, 150, 56, 20))
        self.leTgtUser = QLineEdit(self.grpTgt)
        self.leTgtUser.setObjectName(u"leTgtUser")
        self.leTgtUser.setGeometry(QRect(70, 150, 121, 20))
        self.lbTgtPasswd = QLabel(self.grpTgt)
        self.lbTgtPasswd.setObjectName(u"lbTgtPasswd")
        self.lbTgtPasswd.setGeometry(QRect(10, 180, 56, 20))
        self.leTgtPasswd = QLineEdit(self.grpTgt)
        self.leTgtPasswd.setObjectName(u"leTgtPasswd")
        self.leTgtPasswd.setGeometry(QRect(70, 180, 121, 20))
        self.lbTgtRdbms = QLabel(self.grpTgt)
        self.lbTgtRdbms.setObjectName(u"lbTgtRdbms")
        self.lbTgtRdbms.setGeometry(QRect(10, 30, 56, 20))
        self.comboBox_2 = QComboBox(self.grpTgt)
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.setObjectName(u"comboBox_2")
        self.comboBox_2.setGeometry(QRect(70, 30, 121, 20))
        self.comboBox_2.setEditable(False)
        self.pbTgtTestConn = QPushButton(self.grpTgt)
        self.pbTgtTestConn.setObjectName(u"pbTgtTestConn")
        self.pbTgtTestConn.setGeometry(QRect(220, 30, 111, 23))
        self.grpTab = QGroupBox(self.centralWidget)
        self.grpTab.setObjectName(u"grpTab")
        self.grpTab.setGeometry(QRect(20, 240, 721, 471))
        self.trSrcTables = QTreeWidget(self.grpTab)
        __qtreewidgetitem = QTreeWidgetItem(self.trSrcTables)
        QTreeWidgetItem(__qtreewidgetitem)
        QTreeWidgetItem(__qtreewidgetitem)
        QTreeWidgetItem(self.trSrcTables)
        self.trSrcTables.setObjectName(u"trSrcTables")
        self.trSrcTables.setGeometry(QRect(10, 10, 321, 451))
        self.teQuery = QPlainTextEdit(self.grpTab)
        self.teQuery.setObjectName(u"teQuery")
        self.teQuery.setGeometry(QRect(380, 10, 331, 71))
        self.pbConfirm = QPushButton(self.grpTab)
        self.pbConfirm.setObjectName(u"pbConfirm")
        self.pbConfirm.setGeometry(QRect(510, 90, 75, 23))
        self.pbPlus = QPushButton(self.grpTab)
        self.pbPlus.setObjectName(u"pbPlus")
        self.pbPlus.setGeometry(QRect(340, 170, 31, 31))
        self.pbPlus.setLayoutDirection(Qt.LeftToRight)
        self.pbMinus = QPushButton(self.grpTab)
        self.pbMinus.setObjectName(u"pbMinus")
        self.pbMinus.setGeometry(QRect(340, 210, 31, 31))
        self.pbMinus.setLayoutDirection(Qt.LeftToRight)
        self.trMigTables = QTreeWidget(self.grpTab)
        __qtreewidgetitem1 = QTreeWidgetItem(self.trMigTables)
        QTreeWidgetItem(__qtreewidgetitem1)
        QTreeWidgetItem(__qtreewidgetitem1)
        QTreeWidgetItem(self.trMigTables)
        self.trMigTables.setObjectName(u"trMigTables")
        self.trMigTables.setGeometry(QRect(380, 120, 331, 341))
        self.pbOptions = QPushButton(self.centralWidget)
        self.pbOptions.setObjectName(u"pbOptions")
        self.pbOptions.setGeometry(QRect(300, 720, 75, 23))
        self.pbStart = QPushButton(self.centralWidget)
        self.pbStart.setObjectName(u"pbStart")
        self.pbStart.setGeometry(QRect(380, 720, 75, 23))
        MainWindow.setCentralWidget(self.centralWidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 760, 21))
        self.menuTest = QMenu(self.menubar)
        self.menuTest.setObjectName(u"menuTest")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuTest.menuAction())

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.grpSrc.setTitle(QCoreApplication.translate("MainWindow", u"Source", None))
        self.lbSrcHost.setText(QCoreApplication.translate("MainWindow", u"Host IP", None))
        self.lbSrcPort.setText(QCoreApplication.translate("MainWindow", u"Port", None))
        self.lbSrcDB.setText(QCoreApplication.translate("MainWindow", u"DB (SID)", None))
        self.lbSrcUser.setText(QCoreApplication.translate("MainWindow", u"User", None))
        self.lbSrcPasswd.setText(QCoreApplication.translate("MainWindow", u"Password", None))
        self.lbSrcRdbms.setText(QCoreApplication.translate("MainWindow", u"RDBMS", None))
        self.cbSrcDbms.setItemText(0, QCoreApplication.translate("MainWindow", u"Oracle", None))

        self.cbSrcDbms.setCurrentText(QCoreApplication.translate("MainWindow", u"Oracle", None))
        self.pbSrcTestConn.setText(QCoreApplication.translate("MainWindow", u"Test Connection", None))
        self.pbSrcConn.setText(QCoreApplication.translate("MainWindow", u"Connection", None))
        self.grpTgt.setTitle(QCoreApplication.translate("MainWindow", u"Target", None))
        self.lbTgtHost.setText(QCoreApplication.translate("MainWindow", u"Host IP", None))
        self.lbTgtPort.setText(QCoreApplication.translate("MainWindow", u"Port", None))
        self.lbTgtDB.setText(QCoreApplication.translate("MainWindow", u"DB (SID)", None))
        self.lbTgtUser.setText(QCoreApplication.translate("MainWindow", u"User", None))
        self.lbTgtPasswd.setText(QCoreApplication.translate("MainWindow", u"Password", None))
        self.lbTgtRdbms.setText(QCoreApplication.translate("MainWindow", u"RDBMS", None))
        self.comboBox_2.setItemText(0, QCoreApplication.translate("MainWindow", u"Oracle", None))
        self.comboBox_2.setItemText(1, QCoreApplication.translate("MainWindow", u"MySQL", None))

        self.comboBox_2.setCurrentText(QCoreApplication.translate("MainWindow", u"Oracle", None))
        self.pbTgtTestConn.setText(QCoreApplication.translate("MainWindow", u"Test Connection", None))
        self.grpTab.setTitle("")
        ___qtreewidgetitem = self.trSrcTables.headerItem()
        ___qtreewidgetitem.setText(0, QCoreApplication.translate("MainWindow", u"1", None));

        __sortingEnabled = self.trSrcTables.isSortingEnabled()
        self.trSrcTables.setSortingEnabled(False)
        ___qtreewidgetitem1 = self.trSrcTables.topLevelItem(0)
        ___qtreewidgetitem1.setText(0, QCoreApplication.translate("MainWindow", u"aa", None));
        ___qtreewidgetitem2 = ___qtreewidgetitem1.child(0)
        ___qtreewidgetitem2.setText(0, QCoreApplication.translate("MainWindow", u"tab1", None));
        ___qtreewidgetitem3 = ___qtreewidgetitem1.child(1)
        ___qtreewidgetitem3.setText(0, QCoreApplication.translate("MainWindow", u"tab2", None));
        ___qtreewidgetitem4 = self.trSrcTables.topLevelItem(1)
        ___qtreewidgetitem4.setText(0, QCoreApplication.translate("MainWindow", u"New Item", None));
        self.trSrcTables.setSortingEnabled(__sortingEnabled)

        self.pbConfirm.setText(QCoreApplication.translate("MainWindow", u"Confirm", None))
        self.pbPlus.setText(QCoreApplication.translate("MainWindow", u"+", None))
        self.pbMinus.setText(QCoreApplication.translate("MainWindow", u"-", None))
        ___qtreewidgetitem5 = self.trMigTables.headerItem()
        ___qtreewidgetitem5.setText(0, QCoreApplication.translate("MainWindow", u"1", None));

        __sortingEnabled1 = self.trMigTables.isSortingEnabled()
        self.trMigTables.setSortingEnabled(False)
        ___qtreewidgetitem6 = self.trMigTables.topLevelItem(0)
        ___qtreewidgetitem6.setText(0, QCoreApplication.translate("MainWindow", u"aa", None));
        ___qtreewidgetitem7 = ___qtreewidgetitem6.child(0)
        ___qtreewidgetitem7.setText(0, QCoreApplication.translate("MainWindow", u"tab1", None));
        ___qtreewidgetitem8 = ___qtreewidgetitem6.child(1)
        ___qtreewidgetitem8.setText(0, QCoreApplication.translate("MainWindow", u"tab2", None));
        ___qtreewidgetitem9 = self.trMigTables.topLevelItem(1)
        ___qtreewidgetitem9.setText(0, QCoreApplication.translate("MainWindow", u"New Item", None));
        self.trMigTables.setSortingEnabled(__sortingEnabled1)

        self.pbOptions.setText(QCoreApplication.translate("MainWindow", u"Options", None))
        self.pbStart.setText(QCoreApplication.translate("MainWindow", u"Start", None))
        self.menuTest.setTitle(QCoreApplication.translate("MainWindow", u"\uba54\ub274", None))
    # retranslateUi

